language: php

php:
  - 7.1

before_script:
  - composer install --no-interaction

script:
  - php bin/console server:run
  - phpunit
  - vendor/bin/behat
  - vendor/bin/phploc src

notifications:
  email:
    - kedorev@gmail.com