language: php

php:
  - 7.1

cache:
  directories:
    - $HOME/.composer/cache/files


before-install:
  - composer install


script:
  - phpunit
  - vendor/bin/behat
  - vendor/bin/phploc src

notifications:
  email:
    - kedorev@gmail.com