<?php

namespace MainAppBundle\Repository;

/**
 * AbilitiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbilitiesRepository extends \Doctrine\ORM\EntityRepository
{
}
