<?php

namespace MainAppBundle\Repository;

/**
 * CONSTANTRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CONSTANTRepository extends \Doctrine\ORM\EntityRepository
{
}
