<?php

namespace MainAppBundle\Repository;
use MainAppBundle\Entity\Language;

/**
 * FormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTraduction(Language $lang)
    {

    }
}
