<?php

namespace MainAppBundle\Repository;

/**
 * FormationLanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationLanRepository extends \Doctrine\ORM\EntityRepository
{
}
