<?php

namespace MainAppBundle\Repository;

/**
 * squadRequirementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class squadRequirementRepository extends \Doctrine\ORM\EntityRepository
{
}
