<?php

namespace MainAppBundle\Repository;

/**
 * SquadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SquadRepository extends \Doctrine\ORM\EntityRepository
{


    public function getAllSquadFromFactionWithoutExec($factionId)
    {
    $query = $this->createQueryBuilder('s')
        ->join("s.faction", 'f')
        ->where("f.id = :factionId")
        ->setParameter("factionId", $factionId);
    return $query;
    }


}
