<?php

namespace MainAppBundle\Repository;

/**
 * SquadTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SquadTypeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllSquadTypeOrderByShow()
    {
        $query = $this->createQueryBuilder('s')
            ->orderBy("s.showOrder");
        return $query->getQuery()->getResult();
    }
}
