<?php

namespace MainAppBundle\Repository;

/**
 * StratagemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StratagemRepository extends \Doctrine\ORM\EntityRepository
{
}
