<?php

namespace MainAppBundle\Repository;

/**
 * Weapons_ModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Weapons_ModelRepository extends \Doctrine\ORM\EntityRepository
{
}
