<?php

namespace MainAppBundle\Repository;

/**
 * weaponEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class weaponEntityRepository extends \Doctrine\ORM\EntityRepository
{
    public function getWeaponFromWeaponList($weaponListId)
    {
        $query = $this->createQueryBuilder('we')
            ->join('we.weaponModel',"wm")
            ->join("wm.weaponLists", 'wl')
            ->where("wl.id = :listId")
            ->setParameter("listId", $weaponListId);
        return $query;
    }
}


