main_app_model_entity:
    resource: "@MainAppBundle/Controller/ModelEntityController.php"
    type:     annotation


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

main_app_squads_entity:
    resource: "@MainAppBundle/Controller/SquadsEntityController.php"
    type:     annotation

main_app_formation_entity:
    resource: "@MainAppBundle/Controller/FormationEntityController.php"
    type:     annotation

main_app:
    resource: "@MainAppBundle/Controller"
    type:  annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc