<?php

namespace MainAppBundle\Repository;

/**
 * FactionTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactionTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
