<?php

namespace MainAppBundle\Repository;

/**
 * FormationRequirementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationRequirementRepository extends \Doctrine\ORM\EntityRepository
{
}
