<?php

namespace MainAppBundle\Repository;

/**
 * FormationEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
