<?php

namespace MainAppBundle\Repository;

/**
 * ModelEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModelEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
