<?php

namespace MainAppBundle\Repository;
use MainAppBundle\Entity\squadRequirement;

/**
 * ModelsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class ModelsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllModelByFaction(string $faction)
    {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder();
        $query->select('m');
        $query->from("MainAppBundle:Models",'m');
        $query->innerJoin('m.factionKeyWord','f');
        $query->where("f.name = :faction");
        $query->setParameter("faction",$faction);
        return $query->getQuery()->getResult();
    }

    public function getAllModelFromSquadWithoutExec($squadId)
    {
        $query = $this->createQueryBuilder('m')
            ->join("m.requirementSquad", 'rs')
            ->join('rs.squad', 's')
            ->where("s.id = :squadId")
            ->setParameter("squadId", $squadId);
        return $query;
    }
}
