<?php

namespace MainAppBundle\Repository;

/**
 * PsychicCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PsychicCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
