<?php

namespace MainAppBundle\Repository;

/**
 * PsychicPowerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PsychicPowerRepository extends \Doctrine\ORM\EntityRepository
{
}
