<?php

namespace MainAppBundle\Repository;

/**
 * SquadsEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SquadsEntityRepository extends \Doctrine\ORM\EntityRepository
{

}
