<?php

namespace MainAppBundle\Repository;

/**
 * VisibilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisibilityRepository extends \Doctrine\ORM\EntityRepository
{
}
