<?php

namespace MainAppBundle\Repository;

/**
 * weaponListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class weaponListRepository extends \Doctrine\ORM\EntityRepository
{
}
