<?php

namespace MainAppBundle\Repository;

/**
 * agreementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class agreementRepository extends \Doctrine\ORM\EntityRepository
{
}
