<?php

namespace MainAppBundle\Repository;
use MainAppBundle\Entity\FactionType;

/**
 * FactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllSortByName()
    {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder();
        $query->select('f');
        $query->from("MainAppBundle:Faction",'f');
        $query->orderBy("f.name");
        return $query->getQuery()->getResult();
    }



    public function getTypeFactionSortByName(FactionType $type)
    {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder();
        $query->select('f');
        $query->from("MainAppBundle:Faction",'f');
        $query->orderBy("f.name");
        $query->where("f.type = :type");
        $query->setParameter("type", $type);
        return $query->getQuery()->getResult();
    }

}
