<?php

namespace MainAppBundle\Repository;

/**
 * KeyWordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KeyWordRepository extends \Doctrine\ORM\EntityRepository
{
}
