<?php

namespace MainAppBundle\Repository;

/**
 * ProfilEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfilEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
