<?php

namespace MainAppBundle\Repository;

/**
 * SubFactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubFactionRepository extends \Doctrine\ORM\EntityRepository
{
}
