services:
    admin.Models:
        class: MainAppBundle\Admin\ModelsAdmin
        arguments: [~, MainAppBundle\Entity\Models, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Models }
        public: true
    admin.Faction:
        class: MainAppBundle\Admin\FactionAdmin
        arguments: [~, MainAppBundle\Entity\Faction, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Faction }
        public: true